name: "publish"

on:
  push:
    branches:
      - main 
      - mbudak21-CI-patches

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest"
          #   args: "--target aarch64-apple-darwin"
          # - platform: "macos-latest"
          #   args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          # - platform: "windows-latest"
          #   args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }} # Ensures proper authentication for private submodules
          submodules: recursive # Ensures submodules are initialized and updated

      # - name: Authenticate submodules
      #   run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        
      # - name: Double Fetch submodules
      #   run: |
      #     git submodule sync --recursive
      #     git submodule update --init --recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: deno install
        
      - name: Extract Version from Cargo.toml
        id: extract_version
        run: |
          version=$(grep '^version = ' src-tauri/Cargo.toml | cut -d'"' -f2)
          echo "VERSION=$version" >> $GITHUB_ENV
        shell: bash

      - name: Build Tauri app
        run: deno task tauri build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tagName: app-v${{ env.VERSION }}
          releaseName: "App v${{ env.VERSION }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          
      # Step to create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}" # Replace __VERSION__ dynamically or use a static tag
          release_name: "App v${{ env.VERSION }}"
          body: |
            Release notes for version ${{ env.VERSION }}.
            See the assets below to download this release.
          draft: false
          prerelease: false

      # Upload macOS .dmg as a release asset
      - name: Upload macOS .dmg artifact
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
            src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
          asset_name: jester-desktop-macos.dmg
          asset_content_type: application/x-apple-diskimage

      # Upload macOS .app.tar.gz as a release asset
      - name: Upload macOS .app.tar.gz artifact
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.tar.gz
            src-tauri/target/x86_64-apple-darwin/release/bundle/macos/*.tar.gz
          asset_name: jester-desktop-macos.tar.gz
          asset_content_type: application/gzip

      # Upload Linux and Windows binaries as release assets
      - name: Upload Linux and Windows artifacts
        if: matrix.platform == 'ubuntu-22.04' || matrix.platform == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/**/*.*
          asset_name: jester-desktop-${{ matrix.platform }}.zip
          asset_content_type: application/zip
